### ISSUE TITLE
留言系统 github授权后 对话框消失

### ISSUE THREAD

**Issue by Nelocage** [zerovip/bcsu#7]
您好,有幸拜读了您的博客,非常精彩. 但是留言的时候,github授权后,留言的对话框就消失了.另外zer0zero@yahoo.com 该邮箱似乎已不可用

**Comment by Nelocage** [comment]
> 您好,有幸拜读了您的博客,非常精彩. 但是留言的时候,github授权后,留言的对话框就消失了.另外[zer0zero@yahoo.com](mailto:zer0zero@yahoo.com) 该邮箱似乎已不可用

不好意思,非常抱歉,我刚才重新试了一下.授权后,原本的div应该已经不在了,而要在DOM树中添加了新的div(我瞎猜的) 导致刚进页面的前几秒,滑到底部,没有留言对话框,过了几秒加载完成后,再向下滑动,对话框就出来了,应该是我网速的问题,不好意思

**Comment by zerovip** [comment]
@Nelocage 您好！才看到这条。对话框没有消失就好！我的邮箱地址是 zer0zero-blog@yahoo.com，是不是您看错了？我应该没有写错。欢迎随时来信交流~
